### ISSUE TITLE
Candidates Unable to Join XEHub through Link

### ISSUE THREAD

**Issue by skab16** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#11]
Hello,

My name is Steffi Acevedo, and I'm the president of the Georgia Tech  chapter  (#20) of Chi Epsilon. I have successfully added our candidates for membership for this semester into our Applicants page; however, I've been told by various candidates  that they are not able to click on the link that was included in the email. I've tried to attach a screenshot of what the email looks like. Please, let me know if there's anything I can do from my end. 

Thank you!

Steffi Acevedo

<img width="841" alt="XEHub Candidate Email" src="https://user-images.githubusercontent.com/56938708/67433585-60e53d80-f5b6-11e9-9f36-af903d5e3147.png">

**Comment by brunofvalli** [comment]
Hello Steffi,

 There was an issue in the system that was fixed on Sunday (10/20/2019). If you were to reinvite Emma she would get the new email, actually I have already done for Emma, but you can also do to any other member that might have gotten this bad email.

 To reinvite someone please go to "Member" -> "Applicants" 

![image](https://user-images.githubusercontent.com/5949285/67451477-272c2b00-f5e6-11e9-9ef1-fb7573db5863.png)

 Under the "Invited" tab click on the blue "Reinvite" button next to the person's name.
![image](https://user-images.githubusercontent.com/5949285/67451538-5b075080-f5e6-11e9-89a1-fe934c529be0.png)

On the new screen "Invited" shows up click on the "Invite" button again.
![image](https://user-images.githubusercontent.com/5949285/67451589-7d996980-f5e6-11e9-8785-332a49c07073.png)

All done the person will get an new e-mail with the correct link.

Please create a new case and reference this case if you still have any problems.
