### ISSUE TITLE
Current Members Unable to see Chapter Pages

### ISSUE THREAD

**Issue by skab16** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#15]
**What is the e-mail address you are using to login to xehub**
skab16@gatech.edu

**Describe the bug**
Hello,
It's come to my attention that a current members, James Pressey, of our XE Chapter (#20, Georgia Institute of Technology), has been able to access XEHub but not been able to see anything. It actually asks him to apply for a chapter. We haven't started fully using the XEHub platform, but I want to resolve these issues so that current members are able to see things once we start using it more fully. He's the only one who has approached me with this issue, but I'm not sure how many others could be potentially going through the same problem. 

**To Reproduce**
From his profile:
1. Sign in
2. See homepage with no useful tabs. (see screenshot)

**Expected behavior**
I would expect that as a current member of our chapter (and he is because I found him under our list of members), he would be able to see tabs such as events, chapter, members, etc. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)
![image](https://user-images.githubusercontent.com/56938708/68597895-bf8e3080-046b-11ea-9ff9-f6db6913842f.png)

**Desktop (please complete the following information):** Not sure what he has but I can ask. 

**Smartphone (please complete the following information):** N/A

**Additional context**

**Comment by brunofvalli** [comment]
This is duplication on issue #13 
Please read the issue above for solution.
