### ISSUE TITLE
Incomplete Member List

### ISSUE THREAD

**Issue by vedranakrstic** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#16]
Member list for chapter $143 displays honor members only. How can we add other members to the list? Thank you.
Vedrana Krstic 
krstic@tcnj.edu
Faculty Advisor Chapter #143

**Comment by brunofvalli** [comment]
Try to "Cancel" out of the Member List and go back in. 
![image](https://user-images.githubusercontent.com/5949285/68859167-521d1280-06ac-11ea-8a9e-898b96c76932.png)

If this works let me know. There might be a bug where if you visit another member listing is not resetting the filters.

**Comment by vedranakrstic** [comment]
It worked. Thank you.

**Comment by brunofvalli** [comment]
I have fixed this. It will be implemented in the application after version: 1.15.19318.637
