### ISSUE TITLE
Incomplete Person List

### ISSUE THREAD

**Issue by haydenrandall** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#17]
**What is the e-mail address you are using to login to xehub**
hayden16@nmsu.edu

**Describe the bug**
The person list does not include all members. I noticed that in the Member List, the Membership List value is "0" or "1". What does this mean? The persons with values of "0" are members, and are not showing up on the people list.

**To Reproduce**
1. On "Member" Menu Drop-down, Click "Membership List" notice the zeros in the Membership List column.
![image](https://user-images.githubusercontent.com/57373702/68879531-cb296380-06c6-11ea-9bc5-38195ab354b0.png)

2. Go to "People" menu tab. Search for someone with a "0" as mentioned above. E.g Lucas Rivera:
![image](https://user-images.githubusercontent.com/57373702/68879654-0035b600-06c7-11ea-927e-2479571b07bd.png)
Note that two records are found, however only one is displayed.

**Expected behavior**
All persons with "0" as Membership List value should be listed as members.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.97

**Comment by brunofvalli** [comment]
I will be removing this column. That is the number of "extra" membership a person has.  So a person that is a member of 2 chapters would show a 1. And A person who is also a Chapter Honor Member should show a 1.

**Comment by haydenrandall** [comment]
Ok. But why aren't individuals showing up in the people list?

Hayden A. Randall
NMSU Civil Engineering, Senior & Student Assistant
NMSU LANL Scholar Success Program, Ambassador
NMSU Chi Epsilon Honor Society, Chapter Secretary

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by brunofvalli** [comment]
Found the issue. Will be fixed on the next version after 1.15.19318.637
