### ISSUE TITLE
Applicant registered but not showing up on the "invitation accepted" list

### ISSUE THREAD

**Issue by vedranakrstic** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#19]
TCNJ #143
Applicant: Nicholas Izzo 
Emai: nizzo@eustiseng.com
Other email: nickizzo523@gmail.com
We can't see this applicant among those that have accepted the invitation.

**Comment by vedranakrstic** [comment]
We resolved this issue. The applicant created an account using different email from the one to which the invitation was sent to. Once he recreated the account with the original email he was added to the list of applicants that accepted the invitation.

**Comment by vedranakrstic** [comment]
We have another applicant who registered with a different email. There is problem with a security software at his workplace which is not allowing that email to be used. How can we change his status from invited to invitation accepted?
Applicant: Edward Wilkes
Invitation email: ewilkes@waremalcomb.com (this email is not allowing registration)
Registration email: ewilkes2@gmail.com (applicant registered with this email but we don't see that)
Chapter TCNJ $143

**Comment by brunofvalli** [comment]
You can reject the current invitation and create a new one. 

### To do that
1. Go to Member -> Applicants
1. Select the "Invited" tab
![image](https://user-images.githubusercontent.com/5949285/69116240-3bcada00-0a51-11ea-91fa-3044bc34e5ea.png)
1. Type in a "Log message" on why you are doing this.
1.  Click on "Reject"
![image](https://user-images.githubusercontent.com/5949285/69116258-556c2180-0a51-11ea-9fa3-c3e0e3d4eb9f.png)
1. Invite a person again by clicking on the "Invite a Person" button on the main screen or the one under Member -> Applicant
