### ISSUE TITLE
Issue with clicking on XEHub on ribbon bar still exists

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#2]
When I click on either my name or the XEHub button on the main ribbon tab, I am still being sent to my profile page at least when I'm logged in as a pretend officer.   I need to be able to see the administration page with the buttons and tabs I'm authorized to use highlighted and nothing else.  Something still isn't working correctly.

We've got to get this fixed before we open this to our Beta-test chapters week after next.

**Comment by glenngoss** [comment]
Hum, I see the dropdowns under the ribbon bar headings have been limited somewhat.  We need to get the permissions list fixed as discussed the last time we visited.

**Comment by brunofvalli** [comment]
Hello Glenn,

 Found bug on the alert. Now when you click on the XEHub symbol and get routed to profile the following pop up should display:

![image](https://user-images.githubusercontent.com/5949285/64928232-cd606600-d7da-11e9-8ab1-d3da090e9846.png)


It should let you know what you are missing and you should fill that information to continue.

This will be up in the next update. Also other warnings should start showing up. There was a bug on the pop feature.

This fix will be on a version higher than.
1.14.19256.2359

Please make user to only create cases on the developer issues area:
https://github.com/MBFVSolutionsLLC/ChiEpsilon/issues

**Comment by glenngoss** [comment]
Logged in under alias, only option was the member services GitHub.

Sent from Yahoo Mail on Android 
 
  On Sun, Sep 15, 2019 at 5:05 PM, Bruno<notifications@github.com> wrote:   
Hello Glenn,

Found bug on the alert. Now when you click on the XEHub symbol and get routed to profile the following pop up should display:



It should let you know what you are missing and you should fill that information to continue.

This will be up in the next update. Also other warnings should start showing up. There was a bug on the pop feature.

This fix will be on a version higher than.
1.14.19256.2359

Please make user to only create cases on the developer issues area:
https://github.com/MBFVSolutionsLLC/ChiEpsilon/issues
