### ISSUE TITLE
Officer Access

### ISSUE THREAD

**Issue by skab16** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#20]
**What is the e-mail address you are using to login to xehub**
skab16@gatech.edu

**Describe the bug**
Many of our members, including **officers**, are not able to access our chapter XEHub site. They are able to access a homepage that asks them to apply for a chapter. 

**To Reproduce**
1. Sign in
2. Homepage does not display anything other than "Apply to a Chapter"

**Expected behavior**
I expect the homepages of chapter members to have tabs such as "Events" and "Members". For the officers, I expect their homepages to look like mine, the president. I have access to "People", "Members", "Events", "Order", "Officer", "Chapter", "District", and "Admin". Please allow access to chapter officers, because I will be leaving my position at the end of this month and I don't want our chapter to loose complete access. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)
![image](https://user-images.githubusercontent.com/56938708/69078321-9cccc080-0a05-11ea-929c-097d4979622f.png)
![image](https://user-images.githubusercontent.com/56938708/69078330-a35b3800-0a05-11ea-8f55-c83c43e806a7.png)
![image](https://user-images.githubusercontent.com/56938708/69078384-c554ba80-0a05-11ea-9cac-e41e58fc36a6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brunofvalli** [comment]
Please check issue #13 for instruction on how to request this to be fixed.
You will need to supply some information about each of your chapter officers.

Add a comment at the end of the tread with the following information.
I need to know the following information:
Your full name:
your e-mail addresses (if you have more than one):
The e-mail address you used to sign in:
Your officer position:
Your chapter name and number:
