### ISSUE TITLE
Unable to Reject Invitation

### ISSUE THREAD

**Issue by vedranakrstic** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#21]
Unable to reject invitation. The following error message was displayed:
Access Denied: You cannot Krstic, Vedrana members of chapter ''

We are trying to re-invite Edward Wilkes who is stuck on our list of invited even though he completed registration.
Chapter TCNJ #143

**Comment by brunofvalli** [comment]
This has been fixed. It will be applied on version  1.15.19323.606
