### ISSUE TITLE
Shortcut page does not show all the button

### ISSUE THREAD

**Issue by mohammadihossain** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#25]
**What is the e-mail address you are using to login to xehub**
myemail@mydomain.something

**Describe the bug**
The shortcut page only shows "change personal information" button, it should show other buttons to invite member individually or group to do initiation. I am unable to invite member for initiation. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)
![image](https://user-images.githubusercontent.com/58501951/70117400-07e3dd00-162b-11ea-81de-2fb700fbed97.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brunofvalli** [comment]
It should be back up again. 

Please let me know if it is not.

**Comment by brunofvalli** [comment]
Since I have not heard from you I will assume all is well, if not please reopen the issue, or create a new issue and reference this one.
