### ISSUE TITLE
How do I add people to event?

### ISSUE THREAD

**Issue by haydenrandall** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#26]
**What is the e-mail address you are using to login to xehub**
hayden16@nmsu.edu

**Describe the bug**
I'm trying to take full attendance for our initiation. I need to add Hamid Nemati (hnemati@nmsu.edu) as an initiate who attended, as well as our outgoing and incoming officers.

**To Reproduce**
1. Go to 'Event' dropdown
2. Click on 'Event'
3. Click on detail symbol on the right side of the screen for the intiation event
4. **I Don't see anywhere to add more officers**

**Expected behavior**
I need to add incoming and outgoing officers, and Hamid Nemati, initiate. Hamid is no longer in the applicants tab. I manually added his initation date in earlier on his personal detail page and now mebership type is unknown.

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 79.0.3945.79

**Comment by brunofvalli** [comment]
Has Hamid ever logged into the system? I show Hamid as invited but never accepted the invitation.

**Comment by brunofvalli** [comment]
Hamid needs to login to the system and finished the acceptance of Invitation.

**Comment by brunofvalli** [comment]
I have restored Hamid back to Invited.  I will disable the power to change dates as an officer. You should not have had this power.

**Comment by brunofvalli** [comment]
New version 1.15.19350.2202 now does not allow edit of the initiation date by officers.
