### ISSUE TITLE
No current officers listed for Drexel University

### ISSUE THREAD

**Issue by ghost** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#27]
I am currently the president of the Drexel University chapter, but I am not listed as an officer/do not have any of the shortcuts necessary to invite new members. There are no 'current' officers listed for our chapter but I looked through the past officer list and I was listed as president until 12/11/19 (see picture below). This should be adjusted to 6/14/2020.

![image](https://user-images.githubusercontent.com/59209678/71424050-03c04380-265c-11ea-9920-5c6e6bd0af22.png)

Let me know if any additional information is needed.

**Comment by brunofvalli** [comment]
Hello @callandaley I need your name on the system to assign you.

**Comment by ghost** [comment]
Hi @brunofvalli my name on the system is Callan Daley. As seen in the above screenshot, I am listed as a past officer for Drexel.

**Comment by brunofvalli** [comment]
@callandaley 
I have extended your term until March of next year. Please adjust to the correct date if needed by going here:

https://xehub.azurewebsites.net/Officer/Edit/d96a5619-8505-4e9d-8adb-1e011deec2ca

![image](https://user-images.githubusercontent.com/5949285/71632288-5a38ff00-2bd3-11ea-8b6f-79fb993c4f98.png)
