### ISSUE TITLE
Updating Officer Type of Current Officer

### ISSUE THREAD

**Issue by sarahmondloch** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#28]
Name: Sarah Mondloch
Login Email: smondloch@sdsu.edu
Officer: President
Chapter: San Diego State University #64

One of our current officers was listed as the wrong officer. I created a new officer, but I am unable to delete the incorrect officer position. When I try to delete the incorrect officer it tells me I need to sign into a local account. If I try to edit, it does not complete the action. 

![image](https://user-images.githubusercontent.com/59493712/72182472-61fd5e00-33a0-11ea-8e64-3823bf362b1f.png)

![image](https://user-images.githubusercontent.com/59493712/72182362-282c5780-33a0-11ea-9cc2-f31df8d422f2.png)

How can I remove a current officer?

 - OS: Microsoft
 - Browser: Chrome
 - Version: 10

**Comment by brunofvalli** [comment]
I have fixed this issue. It will be updated as soon.
