### ISSUE TITLE
Drexel University Faculty Adviser is not linked to our chapter

### ISSUE THREAD

**Issue by ghost** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#29]
Hello,
I am the president of the Drexel University chapter, and we are having trouble getting our faculty advisor linked to our chapter's account so he can approve our initiation event. He has registered for the system but does not have the permissions of a faculty advisor, even though I added him as the faculty adviser through the Officer Update feature. (see below screenshot - he is listed twice because I tried adding him again)
![image](https://user-images.githubusercontent.com/59209678/72535205-294d0100-3846-11ea-9068-297f9ec0a280.png)

Also, when I was looking around I accidentally changed his membership status to Unknown by clicking the "Is Default" button under the Member edit page and now I can't change it back to Activated. (see below screenshot)
![image](https://user-images.githubusercontent.com/59209678/72535510-a8dad000-3846-11ea-82c4-328a4e0e864f.png)

Please let me know if you need more information. Thanks.

Faculty Advisor Name: Patrick L. Gurian (GRN 119304, ICN 904)
My name: Callan Daley

**Comment by brunofvalli** [comment]
I have fixed this issue. Basically this is related to issue #13, since Patrick L Gurian logged in an email that was not in the system he created a new record.

**Comment by brunofvalli** [comment]
Patrick L Gurian should be able to login correctly now. Please ask him to log off and log back in and all should be good.

**Comment by ghost** [comment]
@brunofvalli Thank you for addressing the issue with his account. Could you also please fix Patrick Gurian's membership status, as I wrote about in the second half of my post above? The below screenshot is what he sees when he logs in now.

![thumbnail_image004](https://user-images.githubusercontent.com/59209678/72581338-043fa900-38ad-11ea-937d-86d16ae9f1f9.jpg)
