### ISSUE TITLE
Sort function in PEOPLE doesn't seem to be working correctly.

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#3]
Here's what I see when I click on the PEOPLE button.

![image](https://user-images.githubusercontent.com/21148346/64912085-c577c780-d6ef-11e9-8586-2f9ff6f66316.png)

Here's what I see when I sort on last name.

![image](https://user-images.githubusercontent.com/21148346/64912097-fbb54700-d6ef-11e9-9f1a-daddb5956ff1.png)

It appears that the system is sorting only the names shown for records 0 - 100.

When I click on the second pages, this is what I see.

![image](https://user-images.githubusercontent.com/21148346/64912114-361ee400-d6f0-11e9-9e59-9a96cc56eaba.png)

Clearly the entire set of records hasn't been sorted.

Here's what happens when I search for me using my pretend login

![image](https://user-images.githubusercontent.com/21148346/64912136-96ae2100-d6f0-11e9-90d5-e07ce0c85814.png)

This is what I see when I'm logged in as exec.sec

![image](https://user-images.githubusercontent.com/21148346/64912146-aded0e80-d6f0-11e9-9f41-6463c43b5781.png)

**Comment by brunofvalli** [comment]
This was happening only to officer logged in. Sorting was not working for them. This has been fixed. 
Next version after 1.14.19263.2359 will have this fix.
