### ISSUE TITLE
Why is 'Select a Chapter' shown on screen when member logs in?

### ISSUE THREAD

**Issue by glenn-goss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#30]
Working with new 071 Secretary.  Once we got him logged into the system, I noticed that the upper ribbon bar was not displaying correctly. Why is this individual being shown Select a Chapter?

This is dead wrong and needs to be fixed.

![image](https://user-images.githubusercontent.com/28785631/72642727-ab1a5880-3932-11ea-8c6a-6223c319a046.png)

**Comment by brunofvalli** [comment]
The work around to this is the user needs to log off and log back in. His identity changed while he was logged in.
This is not normal operation of the system. That is why it misbehaved.

**Comment by brunofvalli** [comment]
If security information has changed on a user a log-off log-in procedure must be performed.
So if a person has been added as an officer they must be logged off and logged back in for the operation to take effect.
