### ISSUE TITLE
Having issues rejecting candidates from last semester. And not able to login using school email, having to use president's email. 

### ISSUE THREAD

**Issue by Cgarcia258** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#31]
**What is the e-mail address you are using to login to xehub**
cgarcia258@tamu.edu

**Describe the bug**
When using the president's account, we are unable to reject invitations for candidates that did not complete requirements for last semester. It is giving an error message. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brunofvalli** [comment]
What is:
Your full name:

Your chapter name/number:

Your position:

What screen are you trying to reject people? Can you give me one example of a person (full name)?

**Comment by Cgarcia258** [comment]
Full Name: Cesar Garcia

Chapter: Texas A&M University Chapter, I believe the chapter number is #56

Your Position: Chapter Secretary 

It is on the officer approved screen. I am getting the message "Access Denied: You cannot Krishnan, Karthika members of chapter '' when trying to decline the invitation for Jonathan F Pressler. I am getting a similar message when trying to approve applicants. 

Thank you

**Comment by brunofvalli** [comment]
@Cgarcia258 
Please log off and log back in again and you should be good now.
