### ISSUE TITLE
Scheduled Initiation Event Bug 

### ISSUE THREAD

**Issue by gnegym** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#32]
I previously created an event for our initiation date but it doesn't show up on the "Scheduled" tab under the "Event" heading. I am also unable to invite members to the event. When I try to create a new event at the same time, I am unable to do this because it is a 'duplicated event'. I also can't delete the initiation event to try and make a new one.

**Comment by brunofvalli** [comment]
Please answer the questions bellow:
What is your full name?
What e-mail are you using to login to the system?
What is your chapter?
What date and time are you trying to create the event?

**Comment by gnegym** [comment]
Name: Mariah Ann Gnegy
Email: gnegym@vt.edu
Chapter: #018 Virginia Tech
Initiation Date: Wednesday, April 29, 2020 20:00 (8:00 PM EST)

**Comment by brunofvalli** [comment]
Found how to replicate the issue.
Basically if you got an error message when creating the event and clicked the Save button the 2nd time it causes this issue. I have fixed it. It will be updated soon, and I will correct the records.

Going to leave the code update here for my future reference:

```
USE [hubdb]
GO

UPDATE [dbo].[TblEvents]
   SET  [Status] = 1
 WHERE [Status] = 0
GO
```

**Comment by brunofvalli** [comment]
This has been fixed, fixes have been applied.
