### ISSUE TITLE
Resolving XEhub issues to invite new members

### ISSUE THREAD

**Issue by amurtagh18** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#33]
**What is the e-mail address you are using to login to xehub**
amurtagh@stevens.edu

**Describe the bug**
"Chapter #125 has unresolved XEHub issues. These must be cleared before you can initiate new members."

**To Reproduce**
I was attempting to invite new members through the invite a person page and received the error "Chapter #125 has unresolved XEHub issues. These must be cleared before you can initiate new members." I have one member who is stuck in the paid stage because she could not attend initiation but still accepted her invitation to join. I attempted to create a new event, but I received the above error not allowing me to do anything. I also tried to drop her from the system but got the error "Access Denied: You cannot Murtagh, Alexander Richard members of chapter ''"

**Expected behavior**
I thought I would just be able to invite new members into the system without any blocks. Also, I was expecting to be able to drop the candidate from the system so she could reapply. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by brunofvalli** [comment]
You need to contact National Office. Your chapter has been blocked due to unresolved issues.
