### ISSUE TITLE
XEHub Issues for Chapter # 69

### ISSUE THREAD

**Issue by cjgrimm1** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#35]
**What is the e-mail address you are using to login to xehub**
cjgrimm@mail.bradley.edu

**Describe the bug**
Whenever I try to invite the new initiates, I receive an error message telling me that there are unresolved issues with our chapter that need to be taken care of before I can invite people.

**To Reproduce**
1. Go to Members List
2. Click on Invite Member
3. Try to Invite a Member

**Expected behavior**
I expected to be able to invite a member.

**Screenshots**
<img width="941" alt="Capture" src="https://user-images.githubusercontent.com/63881472/79615606-d561ea80-80c8-11ea-9074-c4da6ba5ee1d.PNG">

**Desktop (please complete the following information):**
 
 - Browser chrome

**Comment by johnbbeltran** [comment]
Hello,

I am having the same problem for the Arizona State Chapter #106.

E-mail: jbbeltra@asu.edu

Please let me know if there is any further information required.

Thank you,

John Patrick Beltran

**Comment by brunofvalli** [comment]
Please contact national office. These types of blocks are due to not following Chi Epsilon regulation and not a technical issue. Sorry for the delay.

**Comment by cjgrimm1** [comment]
Could you provide an email for me?

**Comment by brunofvalli** [comment]
You can try Assistant@chi-epsilon.org or office.sec@chi-epsilon.org
