### ISSUE TITLE
Not letting me create event

### ISSUE THREAD

**Issue by tylermccormack** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#36]
I am trying to input the new initiates so I can order their pins and certificates but it won't let create a new event. It will kick me back to the login screen. Once I log in, it keeps me on the login screen but does not change the functionality of my account. This began happening today. I did not experience these issues over the weekend.

**Comment by brunofvalli** [comment]
What e-mail address are you using to login?

**Comment by tylermccormack** [comment]
Mccort3@rpi.edu

**Comment by brunofvalli** [comment]
Sorry forgot to add Full name, chapter name, and officer position.

**Comment by brunofvalli** [comment]
You are no longer the Marshall your Officer term went from 5/4/2019 to 5/4/2020, but the date is on UTC, which is already 5/5/2020.

I have extended you to 5/10/2020. Please make sure to assign new officers for your Chapter.

**Comment by tylermccormack** [comment]
Hi thanks for resolving that. Now I am trying to add two new initiates 
to the event so I can send the list of materials to be purchased but I 
am getting the attached error message when I try to edit the event.

Best,

Tyler

---
Rensselaer Polytechnic Institute
BS Civil Engineering 2020
(609)351-6937

**Comment by tylermccormack** [comment]
Hi I haven't been able to complete the process yet because there have 
been a number of bugs in the website that needed to be resolved. Could 
you please extend me so I can place the order and change the officers.

Best,

Tyler

---
Rensselaer Polytechnic Institute
BS Civil Engineering 2020
(609)351-6937

**Comment by brunofvalli** [comment]
You do know you can extend your own officer Date End by going to the officer screen. Please if you have new issues please create a new issue instead of updating this one.
If you are encountering bugs please report them so they can be fixed.

PS I have not received your attachment on your last entry also please create a new issue with this attachment.
