### ISSUE TITLE
Website error message when I try to edit initiation event

### ISSUE THREAD

**Issue by tylermccormack** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#37]
**What is the e-mail address you are using to login to xehub**
mccort3@rpi.edu

**Describe the bug**
When I try to edit an event in the "taken attendance" status page it boots me to this error page and I cannot complete the action

**To Reproduce**
1. Go to the events tab
2. Click on the "taken attendance tab" 
3. Click on edit at the bottom of the screen

**Expected behavior**
I should be able to edit the event including the members who were there so I can submit the order with everyone who needs pins & certificates 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [windows and chrome]

![error](https://user-images.githubusercontent.com/50425830/81366568-fd85ad80-90b8-11ea-9640-0d45129ddfef.JPG)

**Comment by brunofvalli** [comment]
Looking into this.

**Comment by brunofvalli** [comment]
Just deployed version 1.16.20128.2335 of the application and have fixed this issue.
You should be able to edit the event now.

Thank you for letting me know of this issue and thank you for giving all the details I needed to fix it.
