### ISSUE TITLE
How can I add members to an event?

### ISSUE THREAD

**Issue by tylermccormack** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#38]
**What is the e-mail address you are using to login to xehub**
mccort3@rpi.edu
**Describe the bug**
Two new members are not in the induction event and I cannot add them. Because of this I cannot place the order for pins and certificates. (nicole run and melanie campazano incase you are able to add them in)

**To Reproduce**
1. Go to 'events' tab
2. Click on edit
3. From here there is no way to add members

**Expected behavior**
A way to add members to the list or delete the entire event so I can redo it

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Comment by brunofvalli** [comment]
I cannot find a Nicole Run or Melanie Campazano in the system. Have you gone through the invitation process to invite them in (https://xehub.azurewebsites.net/MemberApplication/Invited)? Only paid candidates can be added to an event.
The candidate is automatically added to any open events.

**Comment by tylermccormack** [comment]
It appears they are both in the system (see error4.jpg) but it will not 
let me add them to the original event with all the other canidates (see 
error3.jpg). I created the 12:15PM event in hopes that I would be able 
to add everyone but it only let me add Nicole Rung and Melanie 
Campozano. Could you please assist me in completing this so I can order 
the pins and certificates for everyone ASAP.

Thanks again for all of your help!

Best,

Tyler

---
Rensselaer Polytechnic Institute
BS Civil Engineering 2020
(609)351-6937

**Comment by brunofvalli** [comment]
I noticed you have an event that was created in the past for 4/30/2020. You cannot change events in the task. You can now accept them into the system by saying they were present. 

Perhaps I am not following what you are trying to do. I cannot see any of your screen shots. Please paste them strait into GitHub. Attached pictures in an e-mail does not get sent to me.
