### ISSUE TITLE
Officers not showing up in Current List

### ISSUE THREAD

**Issue by haydenrandall** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#39]
Hi Bruno, 
I tried to move my self from Vice President to President today, and the Marshal to Vice President. Somehow I did something wrong with the two, and the records are not showing up under present or future. But I know they're in the system somewhere because I got the " After Event Order for Chapter 'New Mexico State University'" email after I submitted attendance for our initiation/officer installation that concluded about an hour ago. I set the approval dates to today (May 8th) for all incoming officers. I found that the officers that I added with start dates of tomorrow (May 9th) show up on the future list. I tried to troubleshoot by re-adding myself as the new President, with a start date of tomorrow rather than today, and I received an error indicated I already had an existing record.

![image](https://user-images.githubusercontent.com/57373702/81457364-02973b00-9153-11ea-876c-b13856191a6c.png)
![image](https://user-images.githubusercontent.com/57373702/81457379-0cb93980-9153-11ea-8706-28afbdba155a.png)

Thanks, 
Hayden Randall
(575)770-9665
hayden16@nmsu.edu

I use Google Chrome Version 81.0.4044.138 for my Windows Laptop.
I am using hayden16@nmsu.edu to login to the XEHub CMS
I am the new President of the New Mexico State University Chapter (#66)

We can also schedule a Zoom meeting if that would be more convenient for you to review the issue.

**Comment by brunofvalli** [comment]
Hello Hayden,

 Sorry for the confusion in the system. It should not allow you to add duplicate records, but I notice something went wrong. 

 When you added the officers did you add them manually? Or did you use the "Import Officer" system?

I have removed the duplication and you should be fine now.

Please let me know. on how you added the officer so I can put a stop on duplication of records.

**Comment by haydenrandall** [comment]
I added the officers manually.

**Comment by haydenrandall** [comment]
Thanks for fixing it!

**Comment by brunofvalli** [comment]
I have added system not to allow overlapping officers to be added. Thank you for letting me know.
