### ISSUE TITLE
Not sure I understand the rational for having edit button available for Chapter and District buttons on ribbon

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#4]
Clicking on the green pencil edit button pulls up another log in screen.  I might see that the FA could be authorized to change chapter information, but I think only HQ should have the ability to adjust District Information.  (Never allow DC's to adjust this data either)

![image](https://user-images.githubusercontent.com/21148346/64912207-93fffb80-d6f1-11e9-99b6-c8c8331fb1f0.png)

Agree to view details, but strongly recommend removing green pencil

![image](https://user-images.githubusercontent.com/21148346/64912238-e3462c00-d6f1-11e9-8cea-f6c6cb38d459.png)

![image](https://user-images.githubusercontent.com/21148346/64912208-a1b58100-d6f1-11e9-9060-66fe2d421bbd.png)

Agree to view details, but strongly recommend removing green pencil 

![image](https://user-images.githubusercontent.com/21148346/64912220-ca3d7b00-d6f1-11e9-8c49-d8ef3939e20a.png)

**Comment by brunofvalli** [comment]
Hello Glenn,
Working on this.
It is done. It took longer than expected right now running through tests. Should be able to deploy tomorrow. If there are any high priority issue please tag it in the system.

**Comment by brunofvalli** [comment]
This has been fixed and it is in the latest version.
More detail can be found here:
https://github.com/MBFVSolutionsLLC/ChiEpsilon
