### ISSUE TITLE
Accidentally changed membership status to "unknown" and deleted initiation date

### ISSUE THREAD

**Issue by kmbyap** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#40]
kmyap@berkeley.edu
#007 - UC Berkeley

Hi, I accidentally changed the membership status of one of our members to "unknown" and deleted her initiation date.

One of our incoming officers, Candace Yee, could not log into XEHub. Looking into the issue, I discovered her profile was missing her email address. I added her email and I thought I just pressed save. However, I must have clicked something wrong because her record shows a change and she no longer shows up on our chapter member list.

Thanks for the help!
Katrina

![image](https://user-images.githubusercontent.com/60208017/81752560-86f50100-9466-11ea-9474-83696abee910.png)

**Comment by brunofvalli** [comment]
What is the name of the member that was changed?

**Comment by kmbyap** [comment]
Candace Yee

**Comment by brunofvalli** [comment]
I have reverted your changes and will be investigate how you did this. Since in theory you should not have this power.

**Comment by kmbyap** [comment]
Thank you!
