### ISSUE TITLE
Candidate is not receiving confirmation email when creating an account on XEHUB

### ISSUE THREAD

**Issue by ghost** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#41]
My name is Ashley. I am the current president of chapter 121.
aspain@siue.edu

Southern Illinois University Edwardsville
Chapter number 121

I have an invited candidate who is not receiving her confirmation email after attempting to create an account. After looking through previous issue posts, I asked if she had checked her junk folder and she says she has. Is there any other solution to this issue. Or someone I can put her in contact with. Thanks for the help in advance!

**Comment by dianap100** [comment]
Hello! 
I am having a similar issue with two students. I was able to have HQ override this and move students along in the scheduling/ initiation process. But they still have not received email confirmation and thus are unable to access their account.
Yes they have checked their spam. I even showed them what the email confirmation would look like to no avail.

**Comment by brunofvalli** [comment]
I am working on this issue and trying to find out what is going on.

**Comment by brunofvalli** [comment]
Sorry for the delay. We have been sending e-mails from another e-mail address and this should have this issue. Please let me know if you still have this issue.
