### ISSUE TITLE
Candidate batch rejected

### ISSUE THREAD

**Issue by adellamk** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#42]
I uploaded a candidate batch using the template given over the weekend, but it was rejected. I do not understand why it was rejected or what I need to do differently.

**Comment by brunofvalli** [comment]
Hello Adella,

 Sorry for the huge delay. I did not notice this case.

 I see your uploads here:
![image](https://user-images.githubusercontent.com/5949285/96189859-eae48f80-0f06-11eb-96b3-6a8d355d4591.png)

 You should see this. By clicking on the Download 43 Rejected Record(s) it should give you an reason why the records were rejected:

![image](https://user-images.githubusercontent.com/5949285/96189984-15364d00-0f07-11eb-8fbf-f077f7ee1d04.png)

Looking through the file it seems these records are already in the system:

![image](https://user-images.githubusercontent.com/5949285/96190063-3434df00-0f07-11eb-96d3-2a2004553a96.png)

I am working with Glenn Goss to solve your issue.

**Comment by brunofvalli** [comment]
We have fixed this. 
Your excel spreadsheet has already been uploaded and in theory your candidates should have received e-mails.
