### ISSUE TITLE
I can't schedule an event for a members

### ISSUE THREAD

**Issue by calfome** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#46]
**What is the e-mail address you are using to login to xehub**
calfome@mail.uc.edu

**What is your chapter number and name**
University of Cincinnati Chapter 34

**Describe the bug**
I am unable to schedule a member for our initiation meeting

**To Reproduce**
1.  I was unable to add two members to an initiation event happening on 11/19 and now they were added to a new batch event. I have no idea what to do. 

**Expected behavior**
I expect Kevin Wermuth and Brian Allen to be scheduled for the initiation happening on 11/19 at 7:30 PM.

**Desktop (please complete the following information):**
 - OS: PC
 - Browser Chrome
 - Version Not Sure

**Comment by brunofvalli** [comment]
If you go to this page:
https://xehub.azurewebsites.net/Event/Scheduled/1b3186c7-9c17-41b3-86c7-f3d06c2cdf04

Go to the bottom and you need to approve the EventGroup

![image](https://user-images.githubusercontent.com/5949285/99765323-703dff80-2ac4-11eb-833a-b7bdc2060345.png)

Click on "OfficerApproved" so you can get the EventGroup done. And the whole path must be done All to way to close "Event Group"
