### ISSUE TITLE
Can't extend term for existing Trustees

### ISSUE THREAD

**Issue by vedranakrstic** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#47]
Tried to extend the term of a few existing Trustees and received the following message:
Another 'Trustee' (Santullo, Lauren Marie) for chapter 'College of New Jersey' with overlapping term of 11/23/2019 to 12/31/2021 already exist. There cannot be overlapping terms.

Vedrana Krstic, FA
TCNJ 143

**Comment by brunofvalli** [comment]
I noticed the record has been changed. 
Is this still a problem.
![image](https://user-images.githubusercontent.com/5949285/101234574-3ead6280-3686-11eb-9040-ea0f9b029b50.png)

**Comment by vedranakrstic** [comment]
No, that was not the record I tried to revise. That was the record in
conflict with the three I wanted to extend: Peter Johnson, Leon Collis and
Kimberly Dana. For all three of them I received the same error message.

--
Vedrana Krstic, PhD, PE
Associate Professor
Department of Civil Engineering
The College of New Jersey
Armstrong 177
609-771-2926

**Comment by brunofvalli** [comment]
This has been fixed the software and have update the records for you:
![image](https://user-images.githubusercontent.com/5949285/101308712-20736e00-3810-11eb-998a-91564b7e9071.png)
