### ISSUE TITLE
Question about Resetting Password

### ISSUE THREAD

**Issue by gnegym** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#48]
One of the initiates from our chapter is trying to reset their password after they forgot it but can't find the email in their inbox or spam folder to reset. Any advice for how to reset the password - should I reinvite the person using a different email address so that they can make an account? Thanks

**Comment by brunofvalli** [comment]
What is the e-mail address of the person in question?

**Comment by gnegym** [comment]
monicag@vt.edu

**Comment by gnegym** [comment]
Hi Bruno - just wanted to follow up on this issue and wanted to know if there was any progress. As far as I know, I am unable to submit our chapter order for certificates/keys until this initiate is in the system. Thank you again!

**Comment by brunofvalli** [comment]
Sorry for the huge delay!
I see that monicag@vt.edu has not logged into the system.
The system said all to way back in 12/2/2021 that Monica had not clicked on the confirmation e-mail that was sent to her. I have removed her account, she should be able to register again with a new password.
