### ISSUE TITLE
Can't take event attendance

### ISSUE THREAD

**Issue by vedranakrstic** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#49]
We are trying to take the attendance for the induction event held on 12/5/20 and are receiving an error message that reads:
"Cannot take attendance Event groups have not been all closed. Please close event groups."
Event groups list shows the event stuck at the advisor approval and we can't get past that step.

![em](https://user-images.githubusercontent.com/57674564/101359905-e4b9c200-386a-11eb-8e51-6a424ef88b8a.png)

Vedrana Krstic FA
TCNJ 143

**Comment by brunofvalli** [comment]
In order to finish a event you must have your advisor approve the Event Group. If you don't have an advisor, please contact ChiEpsilon headquarters.
