### ISSUE TITLE
Please verify operation of Event Button using alias identity

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#5]
When I clicked on Event, I was taken to this page.
![image](https://user-images.githubusercontent.com/21148346/64912290-afb7d180-d6f2-11e9-8f7d-bc437dd8777e.png)
It was necessary for me to sort descending order to get to this screen.
![image](https://user-images.githubusercontent.com/21148346/64912304-d413ae00-d6f2-11e9-9e9d-75165e06061c.png)
Both detail buttons led me to this screen
![image](https://user-images.githubusercontent.com/21148346/64912310-f3124000-d6f2-11e9-8744-fa961fffd429.png)

Clicking the BACK button resulted in this error
![image](https://user-images.githubusercontent.com/21148346/64912315-0c1af100-d6f3-11e9-8893-8947cbc60fb6.png)

This is a bug in the system when logged in using an alias or as exec.sec

**Comment by brunofvalli** [comment]
This has been fixed and will be in the next version after 1.14.19260.2148
