### ISSUE TITLE
Trouble Canceling/Deleting an Event

### ISSUE THREAD

**Issue by hunterklly** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#50]
kellyh3@tcnj.edu

The College of New Jersey, Chapter 143

We accidentally created a second event and we are not able to delete or cancel the event.

**Comment by brunofvalli** [comment]
Is this the event in question?
https://xehub.azurewebsites.net/Event/AttendanceTaken/317f6f93-5cb5-4187-a4ab-26b023df8ea5
