### ISSUE TITLE
expected graduation input?

### ISSUE THREAD

**Issue by dianap100** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#52]
Not so much an issue, but think it would be great to be able to see what students are graduating when on XE hub. When students input their information upon joining XEHub there should be an option to see expected graduation. Officer may like to know that information

**Comment by brunofvalli** [comment]
Could you let me know what screen do you think that would be a helpful feature for you?

Thank you.

**Comment by brunofvalli** [comment]
I have not heard back from you. I am closing this issue.
