### ISSUE TITLE
Deleting an unwanted event

### ISSUE THREAD

**Issue by SRhatican** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#53]
**What is the e-mail address you are using to login to xehub**
rhatics1@tcnj.edu

**What is your chapter number and name**
The College of New Jersey Chapter 143

**Describe the bug**
Our prior executive board created an induction event scheduled for 12/5/2020 by mistake. We are unable to delete this event and would like to know how to. 

**To reproduce**
The event in question can be found normally under the events tab. I do not have the means to edit it. 

**Expected behavior**
For the 12/5/2020 event to be deleted in favor of an 5/7/2021 virtual induction event.

**Desktop (please complete the following information):**
OS: Windows on a PC
Browser: Chrome

**Comment by brunofvalli** [comment]
I have delete the event for you
