### ISSUE TITLE
Member Import Rejection

### ISSUE THREAD

**Issue by SRhatican** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#54]
**What is the e-mail address you are using to login to xehub**
rhatics1@tcnj.edu

**What is your chapter number and name**
The College of New Jersey Chapter 143

**Describe the bug**
Both the chapter's president and I (vice president) have attempted to add our chapter's pledges as eligible members, but our uploads have been rejected. An error message on the page will appear saying "you have no rights to invite a new member". A screenshot is attached below.

**To reproduce**
An excel sheet was unloaded under the 'add eligible' tab. We received a 'member import completed' email roughly an hour later with all records being rejected.

**Expected behavior**
I expect for Michelle Andrascik, Rachel Hannah, Sean Healy, Shivani Savalia and Zach Hauptman to be added as eligible members.

**Desktop (please complete the following information):**
OS: Windows on a PC
Browser: Chrome

![XE Screenshot](https://user-images.githubusercontent.com/79218799/108378032-a4fc4880-71d2-11eb-9133-f4b035cf4a09.png)

**Comment by brunofvalli** [comment]
This has been fixed now.
Please try again.
