### ISSUE TITLE
I am having the same issue as the person in the screenshot

### ISSUE THREAD

**Issue by trast1999** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#55]
**What is the e-mail address you are using to login to xehub**
traste@uwplatt.edu

**What is your chapter number and name**
UW-Platteville 077

**Describe the bug**
I get an error message when I try to add a new eligible member. I have the same issue as the person in the screenshot

**To Reproduce**
Clicking on Eligible Member

**Expected behavior**
I get an error message that says I have "no right" to add new members
![Capture](https://user-images.githubusercontent.com/79299931/108464015-fe04c480-7244-11eb-934d-b9004aece1f9.PNG)

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Smartphone (please complete the following information):**
N/A
**Additional context**

**Comment by brunofvalli** [comment]
Sorry for the delay. This should be fixed now. Please try again.
