### ISSUE TITLE
Member cannot move from 'invited' to 'invitation accepted'

### ISSUE THREAD

**Issue by tmpopraw** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#56]
**What is the e-mail address you are using to login to xehub**
tmpopraw@mtu.edu

**What is your chapter number and name**
Chapter #21 - Michigan Technological University

**Describe the bug**
A new member, Taylor D. Stewart, is correctly entering his information and clicking submit, but his member profile will not advance from the 'Invited' tab to the 'Invitation Accepted' tab. If someone could manually move him to the next tab or update his member status to 'undergrad' so we can order his pin and certificate that would be great.

**To Reproduce**
1. Member receives invitation email and click the link within
2. Member creates a username and password
3. Member enters information and clicks 'submit'

**Expected behavior**
When the member accepts the invitation, he should be moved from 'Invited' to 'Invitation Accepted'.

**Screenshots**
![image](https://user-images.githubusercontent.com/82179821/114088385-f647c080-9882-11eb-8e14-5b00e0815f89.png)
![image](https://user-images.githubusercontent.com/82179821/114088455-08c1fa00-9883-11eb-8b20-033452471408.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Chrome  89.0.4389.90

**Additional context**
Other members have not had issues. There are currently two "Taylor D. Stewarts" because I attempted to create a new entry to reinvite him, but this did not work. I cannot delete entries. The correct one is the one with all of his information entered.

**Comment by brunofvalli** [comment]
Found the issue.
There are two accounts for the given user.
I have merged the accounts.
Please request user to logoff and login and accept the invitation.

**Comment by tmpopraw** [comment]
He is accepting the invitation, but it is still not moving him from 'invited' to 'invitation accepted'. Is there a way you can manually move him if this can't be fixed?
