### ISSUE TITLE
Unable to take attendance

### ISSUE THREAD

**Issue by SRhatican** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#58]
**What is the e-mail address you are using to login to xehub**
rhatics1@tcnj.edu

**What is your chapter number and name**
The College of New Jersey Chapter 143

**Describe the bug**
We are unable to take attendance for our induction event. All inductees were present.

**To reproduce**
The event in question can be found normally under the event group tab. Our faculty advisor is unable to take attendance.

**Expected behavior**
To be able to take attendance to confirm that all five inductees were present.

**Desktop (please complete the following information):**
OS: Windows on a PC
Browser: Chrome
![image](https://user-images.githubusercontent.com/79218799/117598393-bc820800-b115-11eb-9f05-959dc462ab8c.png)

**Comment by brunofvalli** [comment]
I am assuming this is the event your are referencing:
https://xehub.azurewebsites.net/Event/Scheduled/7e670f45-1a9b-446f-af8c-6b6bb1c7504f

Are you getting these messages when you open your event?
![image](https://user-images.githubusercontent.com/5949285/117735768-c100fc00-b1bb-11eb-9ebd-feba152fb179.png)

The message above means the National Officer has not approved this event. You can check this by looking at the bottom of the event page under "Event Group List"
![image](https://user-images.githubusercontent.com/5949285/117735687-94e57b00-b1bb-11eb-8d3c-93913545bf13.png)

Please contact National Officer for further detail.

**Comment by brunofvalli** [comment]
I am assuming my last response fixed your issue, I am closing this issue.
