### ISSUE TITLE
Thoughts on Welcome to MBFVSolutions initial screen on sign-in

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#6]
Please find attached proposed modifications to your initial screen sign-in agreement.

[Proposed Welcome to MBFVSolutions.docx](https://github.com/MBFVSolutionsLLC/ChiEpsilonMemberSupport/files/3614089/Proposed.Welcome.to.MBFVSolutions.docx)

Cookies
We employ the use of cookies. By using XEHub CMS website, you consent to the use of cookies in accordance with MBFVSolutions, LLC’s **privacy policy**.

No mention of privacy policy in this document.  Is this an oversight?

License
Unless otherwise stated, MBFVSolutions, LLC and/or it’s licensors own the intellectual property rights for all material on XEHub CMS. All intellectual property rights are reserved. You may view and/or print pages from http://xehub.chi-epsilon.org for your own personal use subject to restrictions set in these terms and conditions.
You may not:
1.	Republish material from http://xehub.chi-epsilon.org
2.	Sell, rent or sub-license material from http://xehub.chi-epsilon.org
3.	Reproduce, duplicate or copy material from http://xehub.chi-epsilon.org

**Redistribute content from MBFVSolutions, LLC (unless content is specifically made for redistribution).**   This seems out of place.  Should this have been item 4?

I've tried to highlight in yellow modifications and additions.  I corrected the indents where needed too.

**Comment by brunofvalli** [comment]
I am adding a Privacy Policy on the next version.

On your document you mention the following right at the start

----
Welcome to the XEHub Candidate 
Management System (CMS)

**Concepts and functionality for the XEHub CMS was developed by Chi Epsilon, Inc.  System programming has been developed in coordination with MBFVSolutions, LLC**, located at 5124 Escambia Terrace, Fort Worth, Texas 76244.
----

The wording here leads me to believe the IP belongs to Chi Epsilon, Inc and not MBFVSolutions.  Am I misunderstanding the statement?

**Comment by glenngoss** [comment]
Oh, my!  You're absolutely right now that I look at it from your prospective.  I'm sorry I didn't see this earlier.  Let me think about how to wordsmith this area so both of us are completely satisfied.  Of course, when you are finally able to start marketing the product to other firms, we'd expect you to remove the wording associated with XE.   More later today.   Once again, I didn't mean to increase your blood pressure.

**Comment by glenngoss** [comment]
You and I need some face to face time next week. I want to go item by item through this agreement, so I understand your reasons for having that item in the agreement.  Secondly, I want to work through the list of things which need to be fixed.  **NOTE: Selected chapters are using this system NOW!**   Please tell me when you are available to meet.  

Here's my second attempt.

[Version 2 Proposed Welcome notes.docx](https://github.com/MBFVSolutionsLLC/ChiEpsilonMemberSupport/files/3659928/Version.2.Proposed.Welcome.notes.docx)

**Comment by glenn-goss** [comment]
Short discussion of status on this issue requested

**Comment by brunofvalli** [comment]
I think we can close this for now.
