### ISSUE TITLE
Need to be given access to the chapter page

### ISSUE THREAD

**Issue by briantag10** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#61]
Hello! I am the new Chi Ep president for the chapter at Stevens Institute of Technology.

I would like to be admitted into the chapter on the chi ep website and given officer power so I can add our new members.

Please get back to me as soon as possible!

**Comment by brunofvalli** [comment]
Please I need your complete name and your e-mail address.

Do you have any proof you have been made president?

**Comment by briantag10** [comment]
Brian Taglialavore
***@***.***

See attached for Proof.[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by briantag10** [comment]
btaglial@stevens.edu

**Comment by brunofvalli** [comment]
You are already the president. I am closing this old issue.
