### ISSUE TITLE
I can not Approve Officers that have been Invited

### ISSUE THREAD

**Issue by briantag10** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#62]

**Comment by brunofvalli** [comment]
@briantag10 
What email are you using to login to the xehub system?

Do you mean you are trying to approve Members? What members in specific are you trying to approve (first last name)?

If you mean Officers what are you trying to do?

**Comment by briantag10** [comment]
For example, Christopher Musante. The list that he’s a part of needs to move forward entirely and I am unable to do so
________________________________

**Comment by brunofvalli** [comment]
Are you getting a message when you click on "Approve" here?

https://xehub.azurewebsites.net/MemberApplication/OfficerApproved/ef5f7ceb-d63c-43c6-8767-113dc33c01f6

![image](https://user-images.githubusercontent.com/5949285/134285269-bfa9d88c-aa1e-48a3-9cac-fd7e92054869.png)

**Comment by briantag10** [comment]
I get an error in the top right corner, "Membership type must be selected" But I can't change it from "Non-member"

**Comment by brunofvalli** [comment]
I believe I have fixed the issue. See if you can go [here](https://xehub.azurewebsites.net/Member/Edit/ef5f7ceb-d63c-43c6-8767-113dc33c01f6) and change his Membership Type

**Comment by briantag10** [comment]
How can I change this membership type?

**Comment by brunofvalli** [comment]
If you go to edit the Member you should be able to click on the "Membership Type"

![image](https://user-images.githubusercontent.com/5949285/135201965-388b441d-e081-45b2-9eab-794b17985b2f.png)

Are you able to go to this link and check if you have the access?
https://xehub.azurewebsites.net/Member/Edit/ef5f7ceb-d63c-43c6-8767-113dc33c01f6

**Comment by briantag10** [comment]
I cannot change Gerard's Membership Type from "Non Member".

This is the error that I keep getting

**Comment by brunofvalli** [comment]
I cannot see the screen shot you are pasting into the e-mail.

You are responding back using e-mail sent to you. Please login to GitHub, there should be a link at the end of this e-mail.

It should look like:

**Comment by brunofvalli** [comment]
This issue has been fixed under ticket #67
