### ISSUE TITLE
Need to be given access to the chapter page

### ISSUE THREAD

**Issue by gerardoreyes98** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#65]
**What is the e-mail address you are using to login to xehub**
gerardo.reyes@students.tamuk.edu

**What is your chapter number and name**
Chapter #135, Texas A&M University - Kingsville.

**Additional context**
Last semester I was elected as the new president for my chapter for this school year. Due to COVID we didn't have any face to face meetings and there was no communication between past officers and members. I was elected but I don't have officer power so I can add our new members, or give power to the other officers. Who is the person in charge of this? Or faculty advisor or who can I email about it? 

Thank you, hope to hear from you soon.

**Comment by brunofvalli** [comment]
I found a record showing your are the current President.
Someone must have helped you already.
Closing the issue.
