### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by gnegym** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#66]
Email: gnegym@vt.edu 
Chapter: Virginia Tech #018

One of my initiates (stevenfm@vt.edu) is unable to log-in to the system. He tried logging in on his phone which created an issue that caused him to be unable to log-in on his computer. He tried to reset his password but never received an email so I believe his profile will need to be deleted so that I can re-invite him. 

Let me know if you need more info from me, thanks in advance!

**Comment by brunofvalli** [comment]
I found stevenfm@vt.edu information at
https://xehub.azurewebsites.net/Person/Detail/7cc32abe-fddb-4d25-a969-d4e2e16ccb6b
Please ask Steven Frank Manolios to re-register and the account should lock in with his internal record.

![image](https://user-images.githubusercontent.com/5949285/140459841-55253539-2352-448a-a6de-de7a35044126.png)

**Comment by brunofvalli** [comment]
I am closing this issue assuming this has been fixed.
I noticed user has not confirmed e-mail yet.

It could mean user is getting e-mail routed to it's spam mailbox.

**Comment by brunofvalli** [comment]
Please let me know if you have any more issues.
