### ISSUE TITLE
Change Member Status from NonMember

### ISSUE THREAD

**Issue by gnegym** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#67]
Email: gnegym@vt.edu
Chapter: Virginia Tech #018

I batch uploaded this semester's initiates and it set everyone's member status to "NonMember" but I am unable to change it to "Undergraduate" and therefore the system will not let me approve any of them. 

1. Go to "Member" >> "Candidate" >> "Invitation Accepted"
2. Click on any of the initiates who have accepted the invitation.
3. Click on the green pencil icon at the bottom of the screen.
4. Click on green "Member Edit" at the bottom of the screen.
(See screenshot)

Expected Behavior: Change "NonMember" to "Undergraduate" via a dropdown menu.

OS: macOS Big Sur Version 11.6; Safari Version 15.0 (I had this same issue when using Google Chrome Version 95.0.4638.69)
![Screen Shot 2021-11-03 at 2 16 37 PM](https://user-images.githubusercontent.com/41524323/140169394-0c5d3662-8065-4ba6-969e-97008bf664e0.png)

**Comment by brunofvalli** [comment]
I found 4 members
https://xehub.azurewebsites.net/MemberApplication?status=InvitationAccepted
I have reset them to Ungraduates for right now and will look into fixing the edit issue.

**Comment by gnegym** [comment]
Great, thank you! I was able to get those 4 into the system. I have 8 more initiates (waiting for them to accept the invitation) that will also need changed once they accept.

**Comment by brunofvalli** [comment]
I have fixed the issue that was causing the Non-Member type. You should not  see these issue anymore.
I have updated all the Non-Member to be Undergraduate.

**Comment by brunofvalli** [comment]
Closing this issue since the latest fix should have fixed this once and for all.
