### ISSUE TITLE
Cannot delete an officer from list

### ISSUE THREAD

**Issue by algold2** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#69]
**What is the e-mail address you are using to login to xehub**
algold2@uky.edu

**What is your chapter number and name**
58 University of Kentucky UKXE
**Describe the bug**
I accidentally entered someone as the wrong officer and so I want to delete them. When I go to delete the entry I am redirected to a login screen. Using the credentials I always use to log in to XEhub I click "log in" and then it loops back to the same screen. If I click log in again I am again looped back to the same log in screen.

Though in the first place I am almost certain I made the entry to be an assistant editor and not Marshall... So maybe that is another bug as well?

**To Reproduce**
Officer->officer list->click trashcan to try to delete my Marshall entry-> try to log in-> get looped

**Expected behavior**
I expected that after I clicked the trash can next to the entry I would have deleted that entry without having to log back in

**Desktop (please complete the following information):**

Windows 10
Chrome  96.0.4664.45 (Official Build) (64-bit)

**Additional context**

**Comment by brunofvalli** [comment]
I have fixed this where an officer can now delete other officers. Before only system administrator could delete an officer.

Please let me know if you have any more issues.

**Comment by algold2** [comment]
Thank you!

**Comment by brunofvalli** [comment]
you are welcome.
