### ISSUE TITLE
Can we reset the ChiEpsilonMemberSupport GitHub?

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#7]
On second thought, I should have put my comments about issues observed while I was acting as a fake officer in the admin GitHub.  Could you reinitialize the ChiEpsilonMembersSupport GitHub so there are no issues or closed issues in the system?

**Comment by brunofvalli** [comment]
You should be able to close issue here, but there are no way to delete issues completely if that what you are asking.

**Comment by glenngoss** [comment]
Okay, if you can't erase them then why don't you create a new GitHub with a different title so that the record is clean. You can do this now, because none of the officers or people who have logged in have created any new GitHub issues.
Had I known that you couldn't erase things oh, I would have never put them in the chiepsilonmembersupport GitHub area.  
My intent in asking you to create another GitHub location for member support is to make sure only information coming from the chapters and our members is created in this new area. They should never see the 8 issues I opened thinking this is where I should have put the issues as a fake member. 

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 10, 2019 at 8:11 PM, Bruno<notifications@github.com> wrote:   
Closed #7.
