### ISSUE TITLE
Faculty Adviser approval

### ISSUE THREAD

**Issue by kaylorrain** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#70]
How do I provide faculty adviser approval to an event?

**Comment by brunofvalli** [comment]
Normally when you login to the first page it should have a list of items pending your approval here:

![image](https://user-images.githubusercontent.com/5949285/145904610-fcc4857f-d8f0-4392-a557-ee620e714d0a.png)

Clicking on the **Go** button should take you to the approval page.

**Comment by kaylorrain** [comment]
Oh.
OK, I tried that, and it took me to last year's initiation.
But the strange thing is, we already received an invoice for our 12/2/2021
event. How was that possible if it wasn't approved yet?

How are you, Bruno?
It's been a long time since we saw each other in Arlington.   Kaye Brubaker

**Comment by brunofvalli** [comment]
Sometimes HQ will jump in and approve the ticket, since the Chapter might be waiting for it. If you give me the url of the event I can check what went on.

I am doing Amazing as always :) It has been a long while, this whole COVID thing really messed up the whole human contact thing :)

**Comment by kaylorrain** [comment]
I found this:
https://xehub.azurewebsites.net/Event/Scheduled/d2be32a5-34ca-425b-af87-d9f295388353

It says "Waiting Faculty Adviser Approval," but it did not appear on my
home page to-do list....

Kaye

**Comment by kaylorrain** [comment]
Good morning, I am going to copy/paste below a message of frustration that
I received from my chapter this morning. Is there anyone they could speak
to directly? Thanks! Kaye


Hi Dr. B,

This website is quite confusing for no reason... I'm sorry you have to deal
with it. I see that last December's event was approved; however, the
December 2021 event (event group A) is still "Waiting Faculty Approval".

If I go to "Event" --> 12/2/21 Event "Take Attendance" --> I get this
pop-up: "Cannot take attendance Event Groups have not been all closed.
Please close event Groups". Then if I go back to "Events" and click on the
purple box with the 3 lines and circles, it shows everyone as "Present"...

If I go to "Event" --> 12/2/21 Event "Take Attendance" --> Scroll all the
way down--> I see this:
[image: image.png]
I then click "Detail" and this is what I see:
[image: image.png]
I think we are working backwards and that is what might be causing
difficulties. The National Officer has already approved the group, but you,
the Faculty Advisor, hasn't yet.

Because of the pop-up "Cannot take attendance Event Groups have not been
all closed. Please close event Groups", I went to "Event" --> "Event
Groups" --> and found this Event Group from 2019:
[image: image.png]
I clicked "Detail", and saw that there are no people in this event group,
making me think it was a mistake. I cannot just cancel it, so I think we
might need to go through the whole process of approvals to satisfy the
pop-up in the aforementioned paragraph. I "Officer Approved" this event
group.

I hope this helps. I am also frustrated with this website. It is
unnecessarily challenging and runs slowly. Please let me know if you have
any questions.

Best,


*Chi Epsilon Executive Board*
President -  Shivani Patel
Vice President - Aashini Patel
Secretary - Katie Crawford
Marshal - Jillian Siegel
Treasurer -  Lilia Yousefian
Editor - Andrew Vogelpohl

**Comment by brunofvalli** [comment]
I have not received any of the pictures.
Could you please add them?

**Comment by kaylorrain** [comment]
It might be easier for me to just forward their email (instead of
copy-paste) is this the address I should forward to:
***@***.***

Kaye

**Comment by brunofvalli** [comment]
GitHub remove; any e-mail addresses. I did not get what you just sent me.

**Comment by kaylorrain** [comment]
OK. I'm printing their email to a PDF and attaching it.
Thanks for your help!
Kaye

**Comment by brunofvalli** [comment]
Please login to github and post directly. GitHub takes out pictures and attachments.
https://github.com/MBFVSolutionsLLC/ChiEpsilonMemberSupport/issues/70

**Comment by kaylorrain** [comment]
I am now in GitHub comments area and will try to include the PDF.
[JillianEmailAboutHub.pdf](https://github.com/MBFVSolutionsLLC/ChiEpsilonMemberSupport/files/7722332/JillianEmailAboutHub.pdf)

**Comment by brunofvalli** [comment]
I see the event in question has already been closed.

So I don't think this is an issue anymore. Closing the issue.
