### ISSUE TITLE
Honor Member Induction Attendance

### ISSUE THREAD

**Issue by SRhatican** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#71]
**What is the e-mail address you are using to login to xehub**
rhatics1@tcnj.edu

**What is your chapter number and name**
Chapter 142 - The College of New Jersey

**Describe the bug**
Our newly inducted chapter honor member, Joseph Ettore, does not appear on XEHub, so we can't log his attendance at our induction ceremony which occurred on December 11th.

**To Reproduce**
1. Event Drop-Down Menu
2. Click on Event option
3. Click on 'Taken Attendance'

**Expected behavior**
Joseph Ettore should appear on the event attendance list.

**Desktop (please complete the following information):**
 - OS: macOS (Sierra)

**Comment by brunofvalli** [comment]
It seems the HQ administrator has already initiated this honor member. You don't need to worry about it:

Bellow is Joseph's member log.

![image](https://user-images.githubusercontent.com/5949285/146882411-7e3b0cfc-c352-4cd2-a4d3-6cdf6cafdf98.png)
