### ISSUE TITLE
Duplicate e-mail. Another person already has the e-mail of <email>

### ISSUE THREAD

**Issue by JBWalrider** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#9]
I cannot register because the website says the email is already in use.  I believe this may be because I already registered in person with the president of my chapter so I am already on the list.  You may have to remove all those who have already registered in order to test the new website.  

Please note that when exiting out of the "about" page and attempting to log in normally, I can do so (after verifying my email).  I think this means that I am already registered.  However, after logging in, I am redirected to the "about" page again where I cannot "save" or "cancel" because of the duplicate email error (if I cancel I am redirected to the "about" page again).

**Comment by JBWalrider** [comment]
I am able to have an account but not able to update my profile.  So for now it is fine, but other members may be having this same issue.  I am not quite sure how I got past it the first time.  

By the way, not sure if this should go in here or the other repo, but the website linked here... I am a new member of XE.

Edit: Just talked to another member who has tried; apparently if the primary email is deleted this conflict won't occur.  An email other than the one used to initially sign up can be used, and ONLY that email can be used.  Is this by design? If so, feel free to close the issue, as I will swap my emails out too. 

However I feel like this is not the intent. I suspect that if I were to do this then I would have 2 accounts, one under each email.

**Comment by brunofvalli** [comment]
Hello

 Sorry for the delay.

 The design is the following...

 You get one e-mail address to login that is also assigned to one Person account, that one person account is connected to one Member account that is in turn connected to multiple memberships.

 So if you have a person account that already exists with a given e-mail and you register with that same e-mail your e-mail login gets assign that that person account.

 Only one registration per person account. And even if you have multiple e-mail register to that person only the first one to register takes the account.

 Not sure if the above made sense. But I am closing this issue for now.
